# Generated by Django 5.2.4 on 2025-07-09 13:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('science', 'Science'), ('arts', 'Arts'), ('social science', 'Social Science'), ('mgt science', 'Mgt Science')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.PositiveIntegerField(blank=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('dp', models.ImageField(blank=True, default='images/user-circle.svg', upload_to='images/')),
                ('dob', models.DateField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_subject', models.CharField(max_length=100)),
                ('strength', models.CharField(choices=[('analytical', 'Analytical Thinking'), ('problem_solving', 'Problem Solving'), ('research', 'Research-Oriented'), ('precision', 'Attention to Detail'), ('logical', 'Logical Reasoning'), ('experimental', 'Experimental Skills'), ('creativity', 'Creativity'), ('visual', 'Visual Expression'), ('imaginative', 'Imaginative Thinking'), ('storytelling', 'Storytelling'), ('emotional', 'Emotional Sensitivity'), ('performance', 'Performance Skills'), ('empathy', 'Empathy'), ('communication', 'Communication Skills'), ('observational', 'Observational Skills'), ('teaching', 'Teaching Ability'), ('persuasive', 'Persuasive Ability'), ('leadership', 'Leadership'), ('organization', 'Organizational Skills'), ('numerical', 'Numerical Reasoning'), ('decision_making', 'Decision Making'), ('salesmanship', 'Salesmanship'), ('planning', 'Strategic Planning')], max_length=100)),
                ('interest', models.CharField(choices=[('technology', 'Technology'), ('engineering', 'Engineering'), ('healthcare', 'Healthcare'), ('laboratory', 'Laboratory Work'), ('nature', 'Nature & Environment'), ('programming', 'Programming'), ('drawing', 'Drawing'), ('music', 'Music'), ('fashion', 'Fashion'), ('film', 'Film & Video'), ('acting', 'Acting'), ('design', 'Graphic & Web Design'), ('people', 'Working with People'), ('politics', 'Politics & Governance'), ('education', 'Education'), ('history', 'History'), ('culture', 'Culture & Society'), ('psychology', 'Human Behavior / Psychology'), ('business', 'Business'), ('marketing', 'Marketing'), ('finance', 'Finance'), ('entrepreneurship', 'Entrepreneurship'), ('real_estate', 'Real Estate'), ('ecommerce', 'E-Commerce')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('subject_group', models.CharField(max_length=255)),
                ('strength', models.CharField(choices=[('analytical', 'Analytical Thinking'), ('problem_solving', 'Problem Solving'), ('research', 'Research-Oriented'), ('precision', 'Attention to Detail'), ('logical', 'Logical Reasoning'), ('experimental', 'Experimental Skills'), ('creativity', 'Creativity'), ('visual', 'Visual Expression'), ('imaginative', 'Imaginative Thinking'), ('storytelling', 'Storytelling'), ('emotional', 'Emotional Sensitivity'), ('performance', 'Performance Skills'), ('empathy', 'Empathy'), ('communication', 'Communication Skills'), ('observational', 'Observational Skills'), ('teaching', 'Teaching Ability'), ('persuasive', 'Persuasive Ability'), ('leadership', 'Leadership'), ('organization', 'Organizational Skills'), ('numerical', 'Numerical Reasoning'), ('decision_making', 'Decision Making'), ('salesmanship', 'Salesmanship'), ('planning', 'Strategic Planning')], max_length=100)),
                ('interest', models.CharField(choices=[('technology', 'Technology'), ('engineering', 'Engineering'), ('healthcare', 'Healthcare'), ('laboratory', 'Laboratory Work'), ('nature', 'Nature & Environment'), ('programming', 'Programming'), ('drawing', 'Drawing'), ('music', 'Music'), ('fashion', 'Fashion'), ('film', 'Film & Video'), ('acting', 'Acting'), ('design', 'Graphic & Web Design'), ('people', 'Working with People'), ('politics', 'Politics & Governance'), ('education', 'Education'), ('history', 'History'), ('culture', 'Culture & Society'), ('psychology', 'Human Behavior / Psychology'), ('business', 'Business'), ('marketing', 'Marketing'), ('finance', 'Finance'), ('entrepreneurship', 'Entrepreneurship'), ('real_estate', 'Real Estate'), ('ecommerce', 'E-Commerce')], max_length=100)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.discipline')),
            ],
        ),
    ]
