# Generated by Django 5.2.4 on 2025-07-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='career',
            field=models.ManyToManyField(blank=True, null=True, related_name='assessment', to='core.career'),
        ),
    ]
