# Generated by Django 5.2.4 on 2025-07-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_assessment_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='career',
            field=models.ManyToManyField(blank=True, related_name='assessment', to='core.career'),
        ),
    ]
