STRENGTHS = [
    ('analytical', 'Analytical Thinking'),
    ('problem_solving', 'Problem Solving'),
    ('research', 'Research-Oriented'),
    ('precision', 'Attention to Detail'),
    ('logical', 'Logical Reasoning'),
    ('experimental', 'Experimental Skills'),
    ('creativity', 'Creativity'),
    ('visual', 'Visual Expression'),
    ('imaginative', 'Imaginative Thinking'),
    ('storytelling', 'Storytelling'),
    ('emotional', 'Emotional Sensitivity'),
    ('performance', 'Performance Skills'),
    ('empathy', 'Empathy'),
    ('communication', 'Communication Skills'),
    ('observational', 'Observational Skills'),
    ('teaching', 'Teaching Ability'),
    ('persuasive', 'Persuasive Ability'),
    ('leadership', 'Leadership'),
    ('organization', 'Organizational Skills'),
    ('numerical', 'Numerical Reasoning'),
    ('decision_making', 'Decision Making'),
    ('salesmanship', 'Salesmanship'),
    ('planning', 'Strategic Planning'),
]

INTERESTS = [
    ('technology', 'Technology'),
    ('engineering', 'Engineering'),
    ('healthcare', 'Healthcare'),
    ('laboratory', 'Laboratory Work'),
    ('nature', 'Nature & Environment'),
    ('programming', 'Programming'),
    ('drawing', 'Drawing'),
    ('music', 'Music'),
    ('fashion', 'Fashion'),
    ('film', 'Film & Video'),
    ('acting', 'Acting'),
    ('design', 'Graphic & Web Design'),
    ('people', 'Working with People'),
    ('politics', 'Politics & Governance'),
    ('education', 'Education'),
    ('history', 'History'),
    ('culture', 'Culture & Society'),
    ('psychology', 'Human Behavior / Psychology'),
    ('business', 'Business'),
    ('marketing', 'Marketing'),
    ('finance', 'Finance'),
    ('entrepreneurship', 'Entrepreneurship'),
    ('real_estate', 'Real Estate'),
    ('ecommerce', 'E-Commerce'),
]